apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo
  namespace: default
spec:
  hard:
    pods: "5"
    count/services: "5"
    count/configmaps: "5"
    count/secrets: "5"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    count/deployments.apps: "2"
    fast-disks.storageclass.storage.k8s.io/requests.storage: "20Gi"
    fast-disks.storageclass.storage.k8s.io/persistentvolumeclaims: "8"
